base_url = "https://docs.worldwidetelescope.org/planetarium-guide/1/"
title = "WWT Planetarium Guide"
description = "Setting up and using WWT in planetariums."
theme = "wwtguide"

[extra]
github_base = "https://github.com/WorldWideTelescope/worldwide-telescope-planetarium-guide"
google_analytics_id = "G-D1J49XX0CV"
